name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install cypress
        run: npm install cypress@latest
      - name: Install linter
        run: npm install eslint --save-dev
      - name: Install linter cypress
        run: npm install eslint-plugin-cypress --save-dev
      - name: Run lint
        run: npm run lint
      - name: Run tests
        run: npm run test
      
